### ISSUE TITLE
After reformatting syntax, cursor goes to the bottom

### ISSUE THREAD

**Issue by ratawar** [Hexer10/SPCode#24]
Pressing CTRL+R to reformat syntax sends the text cursor to the bottom of the document and as soon as I want to press the arrow keys to navigate through the piece of code I'm looking at, it takes me completely out of my scope by scrolling to the bottom.

**Comment by Hexer10** [comment]
I'll have to make that the cursor stays at the same caret position

**Comment by Hexer10** [comment]
This should be better with https://github.com/Hexer10/Spcode/commit/1d71b6c367dcb761f49642ff3c6fc5984ab2d372 , still the cursor might not be in the exact position which you would expect

**Comment by Natanel-Shitrit** [comment]
This was fixed in 108c0d9 and released since 1.6.1.0, closed.
