### ISSUE TITLE
[Bug] Having 2 windows and closing the original, prevents future file openings

### ISSUE THREAD

**Issue by ratawar** [Hexer10/SPCode#26]
1- Open a new file
2- Open a second file
3- Drag the second file to a separate window
4- Close the first file
5- Program becomes unable to open future files

![HKahA6dChh](https://user-images.githubusercontent.com/20617661/82903130-e3602200-9f36-11ea-9387-28313c0807de.gif)

**Comment by Hexer10** [comment]
Seems like this has been happening since the first version of SPEdit, I'll dig deeper into it.

**Comment by Natanel-Shitrit** [comment]
Will be fixed in the next release, Closed!😄

**Comment by ratawar** [comment]
Reopened this since it's possible to reproduce the exact same bug.
