### ISSUE TITLE
IDE crashes if current file gets moved from its location

### ISSUE THREAD

**Issue by ratawar** [Hexer10/Spcode#27]
![A8UrNIwkVL](https://user-images.githubusercontent.com/20617661/83271926-e4948780-a1a0-11ea-9c43-fa67b5096fdd.gif)

**Comment by Hexer10** [comment]
I'm working to catch the exception and remove the code from the editor, in the future I want to add also a popup to save the file that was removed.

**Comment by CanadianJeff** [comment]
I wish I saw this post earlier this just happen to me 12x while working hard on a plugin which I had to redo

notepad++ offers crash recovery I think maybe Spcode could do the same?

**Comment by Natanel-Shitrit** [comment]
Apparently fixed when i fixed #26, so that's closed and will be available next release (1.6.0.3).
