### ISSUE TITLE
Autocomplete local variables and functions

### ISSUE THREAD

**Issue by Hexer10** [Hexer10/Spcode#3]
I think that the autocomplete (and IntelliSense) should work even for user defined variable in the current file.

**Comment by Hexer10** [comment]
Done with version `1.3.4.0` but it still has some major issues and doesn't work in .inc files.

**Comment by Aldabeth** [comment]
It is not working for Handles.  Handle dbConnection for example.

**Comment by Hexer10** [comment]
Could you send an example of a not working code?

**Comment by Aldabeth** [comment]
I send it. Just Handle dbConnection;

then when I try to type dbConn nothing happens.

When I try dbConnectio still nothing.

**Comment by Aldabeth** [comment]
Okay, I am sorry. I found it. If you declare it globally, like out of brackets etc. Then is the autocompletition not working. 

`Handle dbConnection = INVALID_HANDLE;

public Plugin myinfo =
{
	name = PLUGIN_NAME,
	author = PLUGIN_AUTHOR,
	description = PLUGIN_DESCRIPTION,
	version = PLUGIN_VERSION,
	url = PLUGIN_URL
};

public void OnPluginStart()
{
	LoadDatabase();
}`

**Comment by Natanel-Shitrit** [comment]
For some reason it doesn't suggest global variables that have been declared with a `#define` or another variable (note: which i think is not possible - declaring a global variable with another variable).

For example:
• SPCode **will** suggest a variable if declared like this:
```
int g_iBar;
int g_iFoo = 1;
float g_fFooBar;
char g_sBarFoo[64];
char g_sFooBarFoo[64] = "Some String";
```
• SPCode **will not** suggest a variable if declared like this:
```
int g_iFoo = SOME_DEFINE; // Doesn't matter if it's really declared or not.
float g_fBar = g_fFoo; // Already said this is not possible in SM but this is still not showing it in autocomplete.
```

**Comment by Natanel-Shitrit** [comment]
Fixed and will be available on next release (already available from 'Actions' Tab), closed.
