### ISSUE TITLE
IDE is always on the secondary monitor

### ISSUE THREAD

**Issue by xqzba** [Hexer10/Spcode#30]
SPCode never starts in my primary monitor, I have tried minimizing -> move to primary -> maximizing -> exit to save the window position but it still opens in the secondary monitor. Not sure if this is present in SPEdit. Just inconvenient having to always move it.

**Comment by ratawar** [comment]
Did you try checking if this happens with other apps as well? Did you try to seek for solutions online about apps opening on the wrong monitor? Quite sure this can't be SPCode specific.

**Comment by xqzba** [comment]
> Did you try checking if this happens with other apps as well? Did you try to seek for solutions online about apps opening on the wrong monitor? Quite sure this can't be SPCode specific.

Yes I have. The method I tried was the solution I got online and it works flawlessly with any app other than SPCode. I think it might be the .NET Framework that SPCode has.

**Comment by Hexer10** [comment]
Unfortunately I'm not able to provide support for this since I do not have two monitors on my pc, and neither do I know how the frameworks handles on which monitor to open the window

**Comment by Natanel-Shitrit** [comment]
I have successfully added a second monitor support, i will PR it when i will add an option to enable / disable it in the settings.

**Comment by Natanel-Shitrit** [comment]
Done 😃

**Comment by Natanel-Shitrit** [comment]
Merged ,Closed!

**Comment by xqzba** [comment]
SPCode remembers which monitor it is open now which is great, but a similar issue now is that it doesn't remember if it is minimized or maximized.

**Comment by Natanel-Shitrit** [comment]
I can add this, i will add it when i have time 😄

**Comment by xqzba** [comment]
> I can add this, i will add it when i have time 😄

Thanks for your help!

**Comment by Natanel-Shitrit** [comment]
Update pushed, Feel free to open a new issue if you need anything else 😃
