### ISSUE TITLE
[Bug] Apostrophe (Single Quote) character causes include files to be parsed incorrectly.

### ISSUE THREAD

**Issue by Natanel-Shitrit** [Hexer10/Spcode#32]
Note: This is the latest version of the standalone version, not tested on the installer version but expected to be the same.

If apostrophe character (`'`) is used in an include file, some of the natives are not getting parsed, hence not presented in the autocomplete suggestions.
Not parsed natives compiles normally when used in plugins because it has nothing to do with ~lysis~the compiler.

Example:
Default `halflife.inc` file (Lines 311 - 338):
![L311-L338](https://user-images.githubusercontent.com/65548905/96375222-4d949000-1180-11eb-9684-2cacc393dffa.png)

You can see the color of `PrecacheSound()`, which is light blue that indicates that it's a defined `native`.
Hence, it will show the definition when clicked inside the parentheses:
![image](https://user-images.githubusercontent.com/65548905/96375308-eaefc400-1180-11eb-83aa-4f0352454fc9.png)

Unlike the example above, `CreateDialog()`, that should be treated same, is colored in a darker blue (that indicates a normal function, not sure, probably.) and does not open the definition when clicked inside the parentheses:
![image](https://user-images.githubusercontent.com/65548905/96375337-28ece800-1181-11eb-945b-5e4bc017f1ef.png)

To fix this i removed the apostrophe character in line 327, in the `#pragma` (that's a "comment", providing additional information to the compiler).

![image](https://user-images.githubusercontent.com/65548905/96375458-c6481c00-1181-11eb-8f7e-7793d93e3230.png)

After force closing SPcode, now the natives below work normally as should be:
![image](https://user-images.githubusercontent.com/65548905/96375503-0a3b2100-1182-11eb-975f-bdf7a062752d.png)

Thanks you for this awesome program and i hope this will help fix this problem.

**Comment by Natanel-Shitrit** [comment]
Looks like a similar problem in #25.

**Comment by Hexer10** [comment]
Seems like spcode doesn't read the the string after `#pragma deprecated <string>` as a string but instead a normal expression, and my guess is that it is trying to match the full `'<string>'`. I'm going to look into it

**Comment by Natanel-Shitrit** [comment]
Looks like it's closing in line 480:
![image](https://user-images.githubusercontent.com/65548905/96375918-abc37200-1184-11eb-985d-cff998b91de3.png)

**Comment by Hexer10** [comment]
Yep, most likely because there it has found a matching `'` to end the string

**Comment by Hexer10** [comment]
Fixed! Now the tokens after a preprocessor directive are ignored until a EOF
