### ISSUE TITLE
Auto check current scripting folder for includes???

### ISSUE THREAD

**Issue by CanadianJeff** [Hexer10/SPCode#36]
I think by default Spcode looks in its own data folder for includes if I make a scripting folder somewhere else on my drive `C:/scripting` for example and put all my custom plugins in here so I can seperate them from the default sourcemod plugins the current folder should have the option of being added to the scripting directory

**Comment by CanadianJeff** [comment]
solved closing

**Comment by ratawar** [comment]
![image](https://user-images.githubusercontent.com/20617661/97135947-92946580-1730-11eb-8fa4-52f832406166.png)
You can add your own scripting directories separated with a semicolon

**Comment by SirDontPlease** [comment]
ok sorry where this is running into a problem is when it comes time to compile does `spcomp` and/or `spcomp.exe` needs to be in each scripting dir?
or can I force 1 folder to be picked for the location of `spcomp` and/or `spcomp.exe`

**Comment by Natanel-Shitrit** [comment]
Closed, you can reopen the issue if you need any more help.
