### ISSUE TITLE
IDE fps problem

### ISSUE THREAD

**Issue by quantum-o** [Hexer10/SPCode#42]
When i turn on Dynamic Autocompletition/Intellisense IDE seems like 10 fps. I turn off this feature and it turn back to normal fps

**Comment by Hexer10** [comment]
This has already been fixed, I'm expecting to push a release soon.

**Comment by Hexer10** [comment]
Done! Please try with the latest version: https://github.com/Hexer10/SPCode/releases/tag/1.6.2.1
