### ISSUE TITLE
Enclose selection instead of replace

### ISSUE THREAD

**Issue by ghost** [Hexer10/SPCode#45]
Feature request: when auto close is enabled (or have a toggle option) and a text is selected enclose it instead of replacing it.

Example: public void `OnPluginStart`() becomes public void "OnPluginStart"() instead of public void ""()
Same goes with [] {} () "" ''.

**Comment by Hexer10** [comment]
That's a feature I surely look forward to

**Comment by Natanel-Shitrit** [comment]
👀 👀 👀 👀 

![](https://user-images.githubusercontent.com/65548905/98290946-0a755200-1fb3-11eb-99fa-c2a9909684c5.gif)
