### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by RaidoNek** [Hexer10/SPCode#48]
Hello, i do not know if it's a bug, but with a default 1.10 spcompiler, i don't see any errors in SPCode. Normal compile.exe says there's an error, but nothing shows up in IDE. It's propably my fault, but i would be happy, if someone would help me. Regards

**Comment by ratawar** [comment]
Hello, quite a late response. Did you manage to solve this?

**Comment by Natanel-Shitrit** [comment]
Please re-open if relevant, for the time being - Closed. 😄
