### ISSUE TITLE
[Bug] Unexpected crash after opening and closing the 'Edit Configurations' window

### ISSUE THREAD

**Issue by renellc** [Hexer10/SPCode#54]
SPCode Version: `1.6.2.1`

An unexpected crash can consistently occur if you open and then close 'Edit Configurations' window. This only happens if the installation path for SPCode was changed from the default path `%APPDATA%/Roaming/spcode`. When this crash occurs, no error or crash logs are generated

Here the bug does not occur on the default installation path:

![spcode-default-install](https://user-images.githubusercontent.com/25127718/105739583-1ce59480-5eed-11eb-97ff-b04fc8d409bd.gif)

Here is the bug occurring after changing the SP default installation path:

![spcode-changed-install1](https://user-images.githubusercontent.com/25127718/105740332-f6742900-5eed-11eb-8c7b-85ab81bd9be5.gif)

**Comment by ratawar** [comment]
![image](https://user-images.githubusercontent.com/20617661/105766685-d027ab00-5f38-11eb-9c29-cc740dd9c58b.png)
caught it - access denied to the Config.xml file it attempts to write to when closing Configs window. Will look into it

**Comment by Hexer10** [comment]
For the time being you can just tell windows to start `Spcode.exe` as administrator and the crash shouldn't happen

**Comment by ratawar** [comment]
This will be commonly addressed at #50.
