### ISSUE TITLE
[Bug] Upload to FTP doesn't work if "Auto Copy After Compile" is checked

### ISSUE THREAD

**Issue by ratawar** [Hexer10/SPCode#57]
I prove this by uploading, reloading a plugin and checking it's hash - every time it gets renewed until I check that box.

https://user-images.githubusercontent.com/20617661/106531489-1cd92c00-64cd-11eb-9bdc-86a1982bf010.mp4

**Comment by Natanel-Shitrit** [comment]
Confirmed Fixed 😄, Closed!
