### ISSUE TITLE
Replace Lysis with web-based version.

### ISSUE THREAD

**Issue by Hexer10** [Hexer10/SPCode#66]
The current implementation of lysis, used by SPCode, hasn't been updated since 2012, a all of the newer plugins cannot be decompiled with it. A solution could be to use a 3rd party service like `https://headlinedev.xyz/lysis/` or even implement a Java interface with the latest Lysis Java implementation.

**Comment by ratawar** [comment]
https://github.com/Hexer10/SPCode/pull/72
