### ISSUE TITLE
[Bug] IDE marks two or more equally named Configs as selected

### ISSUE THREAD

**Issue by ratawar** [Hexer10/SPCode#71]
https://user-images.githubusercontent.com/20617661/107458508-fd787980-6b32-11eb-96cc-ce0006944c50.mp4

Probably stupid to use the Name string to check for them, but there actually isn't any other thing that identify them as unique - might be totally wrong, though.

**Comment by Natanel-Shitrit** [comment]
Add an ID for each config maybe?

**Comment by ratawar** [comment]
> Add an ID for each config maybe?

that's the first thing that came to mind, yes
I'd like to see if I can take advantage of other factors first, I hope I can
