### ISSUE TITLE
Folding breaks when an if-condition contains a string

### ISSUE THREAD

**Issue by bakapear** [Hexer10/SPCode#74]
![Preview Image](https://i.imgur.com/QmJmvcH.png)

As you can see on the left code block, the folding breaks when an if-condition contains a string.
It however behaves normally if the bracket is placed afterwards (code block on the right)

**Comment by Natanel-Shitrit** [comment]
Thanks for reporting the issue, I'm on that now.

**Comment by Natanel-Shitrit** [comment]
Fixed, closed - thanks @bakapear ❤️
