### ISSUE TITLE
Add version to update window

### ISSUE THREAD

**Issue by Bara** [Hexer10/SPCode#79]
Currently it just shows the changelog without any version number, which looks pretty weird.
![image](https://user-images.githubusercontent.com/17928280/108630620-07b94280-7466-11eb-8898-53691043df25.png)

**Comment by Natanel-Shitrit** [comment]
How's this?
![image](https://user-images.githubusercontent.com/65548905/108635631-00576080-7489-11eb-9778-6cb04c3269b6.png)

**Comment by Bara** [comment]
That looks nice 👌🏻

**Comment by Natanel-Shitrit** [comment]
Improved:

https://user-images.githubusercontent.com/65548905/108636348-50d0bd00-748d-11eb-9a7f-f6ee28dfc62a.mp4

**Comment by ratawar** [comment]
This is what we got so far, but I'm pretty sure it'll stay like this - I've been trying to format the release body in a prettier way, but I'm extremely limited by the framework's controls and their capabilities.

It could also be because I'm dumb as a starfish, who knows.

**Comment by ratawar** [comment]
![2R8TBwE2hH](https://user-images.githubusercontent.com/20617661/108644098-5c6fb400-748c-11eb-9a06-376bda869559.gif)
