### ISSUE TITLE
Update do not work correctly

### ISSUE THREAD

**Issue by Bara** [Hexer10/SPCode#80]
It downloads the SPCodeUpdater.exe, after that the exe will executed and this will create a .zip-Archive with the name `updateZipFile.zip`, but nothing more happens.

My current version is the 1.6.2.1 as portable version.

**Comment by Natanel-Shitrit** [comment]
Should be fixed in the next couple minutes, there was a problem with the unzipping.

**Comment by Natanel-Shitrit** [comment]
Fixed manually for 1.7.0.0.
