### ISSUE TITLE
SPCode crashed when selecting text

### ISSUE THREAD

**Issue by IlayBro** [Hexer10/SPCode#85]
It just keeps crashing when I mark these things on the video, And it's crashing A lot for some other reasons.

https://user-images.githubusercontent.com/77070738/111786536-933bbd00-88c6-11eb-8094-9b0422f1c01b.mp4

**Comment by ratawar** [comment]
Thanks for reporting - is this the latest version?

**Comment by ratawar** [comment]
This issue has probably been fixed, I will release a beta/preview version for you to test at our Discord.
https://discord.com/invite/Uf6hMqnkY4

**Comment by Hexer10** [comment]
Thanks for filing an issue and to @ratawar for taking care of this!
Just a side note, the next time you file an issue please use a descriptive title of the issue so other people can easily find out if they have the same problem.
