### ISSUE TITLE
[Request] Please tell me where auto-completed functions come from.

### ISSUE THREAD

**Issue by sniggyfigbat** [Hexer10/SPCode#93]
When SPCode auto-completes a function for me, the *one thing* I really need to know is where that function comes from, so I can quickly inspect the source if I don't perfectly understand what it does.

As far as I can tell, there's no way to make SPCode give me that information.

Please add source info into the function-documentation hover-over, it would save SO much time.

**Comment by maxijabase** [comment]
To see where functions come from, you can either click a function while pressing ctrl to get taken to that function definition, you can press ctrl+shift+f to open the Definitions Window to search for it (which will give you this information) or with your caret you can step between the function's parentheses to trigger the definition tooltip for that function. 

What comes to mind is to add some sort of keyboard shortcut to get taken to the definition of the symbol that's currently selected in the autocompletion list. Does that sound like something you'd prefer?

https://user-images.githubusercontent.com/20617661/127371756-8612a4bc-1a7d-4fd6-96bd-c8e2939b0396.mp4

**Comment by sniggyfigbat** [comment]
Just tested the ctrl-click functionality, and that's exactly what I needed! Brilliant!

If I were to suggest anything, it's that there's no easy way for a fist-time user to discover this sort of functionality. It'd be nice to have a window that comes up on first-time boot which lists a couple of useful hotkeys and tells the user where to find a full list.

**Comment by maxijabase** [comment]
Definitely something to keep in mind. Thank you!
