### ISSUE TITLE
[Feature Request] Alt+Up/Down to shunt lines up and down, and option to make Ctrl-D duplicate instead of delete.

### ISSUE THREAD

**Issue by sniggyfigbat** [Hexer10/SPCode#94]
As a new user who's written a *lot* of code in Visual Studio, these are the two shortcuts that have been really slowing me down in SPCode.

*(By the way, thank you for making alt-drag box-select across multiple lines, it drives me nuts when I have to work without that. So many editors get it wrong.)*

___

## Alt+Up/Down to shunt lines up and down

Simply put, in VS, holding left alt and pressing the up arrow key will swap the line the cursor is on with the line above, essentially moving that entire line up by one. Alt+down does the same (but downwards). This is just a really helpful shortcut that saves me from having to reach for the mouse and shaves ~3 seconds off a simple, common action.

___

## Option to make Ctrl-D duplicate instead of delete.

Quite often, I will want to duplicate a line and then change a couple of parameters in a function call in the duplicate. In VS and Notepad++, this is as simple as pressing in ctrl-D, and it's completely baked into my muscle memory. In SPCode it deletes the line instead, which is annoying.

I'd really appreciate the ability to change this functionality to conform to my muscle memory. I can't seem to find any way to rebind keys (I may have missed a config file, but I did look), but simply adding it as a checkbox in the Editor options would be perfectly sufficient as an easier fix.

___

Naturally, I don't want to seem like I'm demanding features in an entitled way, and if there's already ways of doing these things I'd be thrilled. If nothing else, though, I thought it might be valuable for the dev team here for me to report my pain points as a newcomer.

Many thanks for your work on this excellent tool; it's made working with the (honestly terrifying) SourcePawn ecosystem much more manageable.

**Comment by Natanel-Shitrit** [comment]
### Alt+Up/Down to shunt lines up and down: `Ctrl + ↑ / ↓`
### Option to make Ctrl-D duplicate instead of delete: `Ctrl + Alt + ↑ / ↓`

**Comment by Natanel-Shitrit** [comment]
Hey!

First of all, thank you for the detailed issue.

I am aware that there are differences between SPCode and VSCode (in this case, shortcuts), but those shortcuts are from the original SPEdit software by `JulienKluge`.
Changing the current shortcuts will confuse a lot of people who used SPEdit / SPCode regularly up to this day. 

Sadly, you cannot customize the shortcuts and they are hardcoded into the current SPCode.
And adding a customizable shortcuts system will require a lot of work, and will be harder to implement into the existing code, at least in my opinion.

I will leave this issue open, and i would like to hear what you think, if you have anything else to say.
The best thing is to close this issue and open a new issue regarding the customizable shortcuts system, and hope someone is willing to work hard enough and fulfill such wishes (SPCode is an open-source project and can receive pull requests from anyone).

**Comment by Hexer10** [comment]
## ## # Svxll

**Comment by Hexer10** [comment]
## ## # Svxll

**Comment by sniggyfigbat** [comment]
Understood, thanks.
